--Criando a tabela de videos
CREATE TABLE IF NOT EXISTS t_video (
  ID_VIDEO INTEGER PRIMARY KEY AUTOINCREMENT,
  NOME TEXT NOT NULL,
  ARTISTA TEXT NOT NULL,
  GENERO TEXT,
  URL TEXT NOT NULL
);

--Criando a tabela de usuarios
CREATE TABLE IF NOT EXISTS t_usuarios (
  ID_USUARIO INTEGER PRIMARY KEY AUTOINCREMENT,
  NOME_USUARIO TEXT NOT NULL,
  LOGIN TEXT NOT NULL,
  SENHA TEXT NOT NULL
);

-- Criando a tabela de playlists
CREATE TABLE IF NOT EXISTS t_playlists (
  ID_PLAYLIST INTEGER PRIMARY KEY AUTOINCREMENT,
  NOME_PLAYLIST TEXT NOT NULL,
  DESCRICAO TEXT,
  idVideo INTEGER PRIMARY KEY
);

-- Criando a tabela associativa entre playlists e vídeos
CREATE TABLE IF NOT EXISTS t_playlist_videos (
  ID_PLAYLIST INTEGER NOT NULL,
  ID_VIDEO INTEGER NOT NULL,
  PRIMARY KEY (ID_PLAYLIST, ID_VIDEO),
  FOREIGN KEY (ID_PLAYLIST) REFERENCES t_playlists(ID_VIDEO) ON DELETE CASCADE,
  FOREIGN KEY (ID_VIDEO) REFERENCES t_video(ID_VIEO) ON DELETE CASCADE
);
